/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisis_proyecto;


import java.io.*;
import java.util.*;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardojose
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selec_archive = new javax.swing.JButton();
        generar_archive = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selec_archive.setText("Seleccionar Archivo");
        selec_archive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selec_archiveActionPerformed(evt);
            }
        });

        generar_archive.setText("Generar Rutas");
        generar_archive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_archiveActionPerformed(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generar_archive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selec_archive, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selec_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generar_archive, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selec_archiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selec_archiveActionPerformed
        // TODO add your handling code here:
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setCurrentDirectory(new File("./"));
        int result = jFileChooser.showOpenDialog(new JFrame());
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFileChooser.getSelectedFile();
            File archivo = null;
            FileReader fr = null;
            BufferedReader br = null;
            System.out.println(selectedFile.getAbsolutePath());
            try {
                archivo = new File (selectedFile.getAbsolutePath());
                fr = new FileReader (archivo);
                br = new BufferedReader(fr);
                String num_entradas;
                 int index = 1;
                while ((num_entradas = br.readLine()) != null) {
                    int store = index - 2;
                    switch (index) {
                        case 1:
                           camiones = Integer.parseInt(num_entradas);//camiones
                            break;
                         case 2: {
                             
                           String[] Split = num_entradas.split(",");
                             x.add(Double.parseDouble(Split[0]));
                             y.add(Double.parseDouble(Split[1]));
                            break;
                        }
                        default: {
                            String[] Split = num_entradas.split(",");
                             x.add(Double.parseDouble(Split[0]));
                             y.add(Double.parseDouble(Split[1]));                  
                            break;
                        }
                    }
                    if (store >= 0) {
                        this.texto.append(store + "\t");
                    } else {
                        this.texto.append("\t");
                    }

                    this.texto.append(num_entradas);
                    this.texto.append("\n");
                    index++;
                }
            }
            catch(Exception e){
                e.printStackTrace();
            }finally{
                try{                    
                    if( null != fr ){   
                        fr.close();     
                    }                  
                }catch (Exception e2){ 
                    e2.printStackTrace();
                }
            }
        }
    
    }//GEN-LAST:event_selec_archiveActionPerformed

    private void generar_archiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_archiveActionPerformed
        // TODO add your handling code here:
        texto.setText("");
        matriz = new double[x.size()][x.size()];
            crearMatriz();
            calcularRuta();
            crearArchivo();
        
        
        
        
        
        
    }//GEN-LAST:event_generar_archiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar_archive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selec_archive;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
    static int camiones = 0;
    static List<Double> x = new ArrayList();
    static List<Double> y = new ArrayList();                
    static List<Double> Rutas = new ArrayList();
    static List<Double> distanciasCamiones = new ArrayList();
    static double [][] matriz ;
    
    
    
 public  void calcularRuta(){
       double Ruta = 0;
        for (int i = 1; i < camiones+1; i++) {
            Ruta = Math.sqrt(Math.pow(x.get(i)-x.get(0),2) + Math.pow(y.get(i)-y.get(0), 2));
            Rutas.add(Ruta);
            texto.append("Ruta #"+i+": "+Ruta+"\n");
        }
    }

    public static void crearMatriz(){
        for (int i = 0; i < x.size(); i++) {
            for (int j = 0; j < y.size(); j++) {
                if (i == j) {
                     matriz[i][j] = 0;
                }else{
                    matriz[i][j] = Math.sqrt(Math.pow(x.get(j)-x.get(i),2) + Math.pow(y.get(j)-y.get(i), 2));
                }
            }
        }
    }
    public  void crearArchivo(){
      try {
            File file = new File("./salida.txt");
            file.createNewFile();
            FileWriter fileWriter = new FileWriter(file.getAbsoluteFile());
            try (BufferedWriter bufferWriter = new BufferedWriter(fileWriter)) {
                String salida = texto.getText();
                bufferWriter.write(salida);
                bufferWriter.flush();
            }
            JOptionPane.showMessageDialog(this, "archivo creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
        }    
    }
}

